sudo: required
python:
  - "2.7"

# Clean and don't fail
install:
  - sudo pip install pygments
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.36/hugo_0.36_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0

# Build the website
script:
  - hugo -v

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target-branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
